const pictogram = [
	{
		"name": "ACCIONES",
		"words": [
			{
		        "name":"ABRAZAR",
		        "image":"abrazar.png"
		    },
		    {
		        "name":"ADORNAR",
		        "image":"adornar.png"
		    },
		    {
		        "name":"ARRUGAR",
		        "image":"arrugar.png"
		    },
		    {
		        "name":"AYUDAR",
		        "image":"ayudar.png"
		    },
		    {
		        "name":"BAILAR",
		        "image":"bailar.png"
		    },
		    {
		        "name":"BA\u00d1AR",
		        "image":"banar.png"
		    },
		    {
		        "name":"BEBER",
		        "image":"beber.png"
		    },
		    {
		        "name":"BESAR",
		        "image":"besar.png"
		    },
		    {
		        "name":"BORRAR",
		        "image":"borrar.png"
		    },
		    {
		        "name":"CAER",
		        "image":"caer.png"
		    },
		    {
		        "name":"CAMINAR",
		        "image":"caminar.png"
		    },
		    {
		        "name":"CANTAR",
		        "image":"cantar.png"
		    },
		    {
		        "name":"CERRAR",
		        "image":"cerrar.png"
		    },
		    {
		        "name":"CHUPAR",
		        "image":"chupar.png"
		    },
		    {
		        "name":"COMER",
		        "image":"comer.png"
		    },
		    {
		        "name":"CORRER",
		        "image":"correr.png"
		    },
		    {
		        "name":"COSER",
		        "image":"coser.png"
		    },
		    {
		        "name":"DAR",
		        "image":"dar.png"
		    },
		    {
		        "name":"DISCUTIR",
		        "image":"discutir.png"
		    },
		    {
		        "name":"DORMIR",
		        "image":"dormir.png"
		    },
		    {
		        "name":"EMPUJAR",
		        "image":"empujar.png"
		    },
		    {
		        "name":"ENCENDER",
		        "image":"encender.png"
		    },
		    {
		        "name":"ENSE\u00d1AR",
		        "image":"ensenar.png"
		    },
		    {
		        "name":"ENTRAR",
		        "image":"entrar.png"
		    },
		    {
		        "name":"ESCONDER",
		        "image":"esconder.png"
		    },
		    {
		        "name":"ESCRIBIR",
		        "image":"escribir.png"
		    },
		    {
		        "name":"ESCUCHAR",
		        "image":"escuchar.png"
		    },
		    {
		        "name":"JUGAR",
		        "image":"jugar.png"
		    },
		    {
		        "name":"LAVAR",
		        "image":"lavar.png"
		    },
		    {
		        "name":"LAVARMANOS",
		        "image":"lavarmanos.png"
		    },
		    {
		        "name":"LEER",
		        "image":"leer.png"
		    },
		    {
		        "name":"LIMPIAR",
		        "image":"limpiar.png"
		    },
		    {
		        "name":"LLAMAR",
		        "image":"llamar.png"
		    },
		    {
		        "name":"LLORAR",
		        "image":"llorar.png"
		    },
		    {
		        "name":"MIRAR",
		        "image":"mirar.png"
		    },
		    {
		        "name":"MIRARSE",
		        "image":"mirarse.png"
		    },
		    {
		        "name":"NADAR",
		        "image":"nadar.png"
		    },
		    {
		        "name":"OIR",
		        "image":"oir.png"
		    },
		    {
		        "name":"OLER",
		        "image":"oler.png"
		    },
		    {
		        "name":"PATINAR",
		        "image":"patinar.png"
		    },
		    {
		        "name":"PEGAR",
		        "image":"pegar.png"
		    },
		    {
		        "name":"PEINAR",
		        "image":"peinar.png"
		    },
		    {
		        "name":"PESCAR",
		        "image":"pescar.png"
		    },
		    {
		        "name":"PINTAR",
		        "image":"pintar.png"
		    },
		    {
		        "name":"QUERER",
		        "image":"querer.png"
		    },
		    {
		        "name":"REIR",
		        "image":"reir.png"
		    },
		    {
		        "name":"ROBAR",
		        "image":"robar.png"
		    },
		    {
		        "name":"ROMPER",
		        "image":"romper.png"
		    },
		    {
		        "name":"SALTAR",
		        "image":"saltar.png"
		    },
		    {
		        "name":"SALUDAR",
		        "image":"saludar.png"
		    },
		    {
		        "name":"SECAR",
		        "image":"secar.png"
		    },
		    {
		        "name":"SOPLAR",
		        "image":"soplar.png"
		    },
		    {
		        "name":"SUJETAR",
		        "image":"sujetar.png"
		    },
		    {
		        "name":"TOCAR",
		        "image":"tocar.png"
		    },
		    {
		        "name":"TRABAJAR",
		        "image":"trabajar.png"
		    },
		    {
		        "name":"VESTIR",
		        "image":"vestir.png"
		    }
		]
	},
	{
		"name": "ANIMALES",
		"words": [
			{
		        "name":"ABEJA",
		        "image":"abeja.png"
		    },
		    {
		        "name":"\u00c1GUILA",
		        "image":"aguila.png"
		    },
		    {
		        "name":"ARA\u00d1A",
		        "image":"arana.png"
		    },
		    {
		        "name":"BISONTE",
		        "image":"bisonte.png"
		    },
		    {
		        "name":"BUHO",
		        "image":"buho.png"
		    },
		    {
		        "name":"CABALLO",
		        "image":"caballo.png"
		    },
		    {
		        "name":"CABRA",
		        "image":"cabra.png"
		    },
		    {
		        "name":"CALAMAR",
		        "image":"calamar.png"
		    },
		    {
		        "name":"CAMALEON",
		        "image":"camaleon.png"
		    },
		    {
		        "name":"CANGREJO",
		        "image":"cangrejo.png"
		    },
		    {
		        "name":"CANGURO",
		        "image":"canguro.png"
		    },
		    {
		        "name":"CASTOR",
		        "image":"castor.png"
		    },
		    {
		        "name":"CERDO",
		        "image":"cerdo.png"
		    },
		    {
		        "name":"CIENPI\u00c9S",
		        "image":"cienpies.png"
		    },
		    {
		        "name":"CIERVO",
		        "image":"ciervo.png"
		    },
		    {
		        "name":"COCODRILO",
		        "image":"cocodrilo.png"
		    },
		    {
		        "name":"CONEJO",
		        "image":"conejo.png"
		    },
		    {
		        "name":"DELF\u00cdN",
		        "image":"delfin.png"
		    },
		    {
		        "name":"ELEFANTE",
		        "image":"elefante.png"
		    },
		    {
		        "name":"ERIZO",
		        "image":"erizo.png"
		    },
		    {
		        "name":"ESCORPI\u00d3N",
		        "image":"escorpion.png"
		    },
		    {
		        "name":"ESTRELLA DE MAR",
		        "image":"estrellademar.png"
		    },
		    {
		        "name":"FOCA",
		        "image":"foca.png"
		    },
		    {
		        "name":"GALLO",
		        "image":"gallo.png"
		    },
		    {
		        "name":"GATO",
		        "image":"gato.png"
		    },
		    {
		        "name":"HIPOP\u00d3TAMO",
		        "image":"hipopotamo.png"
		    },
		    {
		        "name":"INSECTO",
		        "image":"insecto.png"
		    },
		    {
		        "name":"JABAL\u00cd",
		        "image":"jabali.png"
		    },
		    {
		        "name":"JIRAFA",
		        "image":"jirafa.png"
		    },
		    {
		        "name":"KOALA",
		        "image":"koala.png"
		    },
		    {
		        "name":"LE\u00d3N",
		        "image":"leon.png"
		    },
		    {
		        "name":"LLAMA",
		        "image":"llama.png"
		    },
		    {
		        "name":"LOBO",
		        "image":"lobo.png"
		    },
		    {
		        "name":"LORO",
		        "image":"loro.png"
		    },
		    {
		        "name":"MAPACHE",
		        "image":"mapache.png"
		    },
		    {
		        "name":"MARIPOSA",
		        "image":"mariposa.png"
		    },
		    {
		        "name":"ORCA",
		        "image":"orca.png"
		    },
		    {
		        "name":"OSO",
		        "image":"oso.png"
		    },
		    {
		        "name":"OVEJA",
		        "image":"oveja.png"
		    },
		    {
		        "name":"PALOMA",
		        "image":"paloma.png"
		    },
		    {
		        "name":"PANDA",
		        "image":"panda.png"
		    },
		    {
		        "name":"PATO",
		        "image":"pato.png"
		    },
		    {
		        "name":"PEREZOSO",
		        "image":"perezoso.png"
		    },
		    {
		        "name":"PERRO",
		        "image":"perro.png"
		    },
		    {
		        "name":"PEZ",
		        "image":"pez.png"
		    },
		    {
		        "name":"PING\u00dcINO",
		        "image":"pinguino.png"
		    },
		    {
		        "name":"RANA",
		        "image":"rana.png"
		    },
		    {
		        "name":"RAT\u00d3N",
		        "image":"raton.png"
		    },
		    {
		        "name":"SERPIENTE",
		        "image":"serpiente.png"
		    },
		    {
		        "name":"TIBUR\u00d3N",
		        "image":"tiburon.png"
		    },
		    {
		        "name":"TIGRE",
		        "image":"tigre.png"
		    },
		    {
		        "name":"TORTUGA",
		        "image":"tortuga.png"
		    },
		    {
		        "name":"VACA",
		        "image":"vaca.png"
		    },
		    {
		        "name":"ZORRO",
		        "image":"zorro.png"
		    }
		]
	},
	{
		"name": "BEBIDAS",
		"words": [
			{
		        "name":"AGUA",
		        "image":"agua.png"
		    },
		    {
		        "name":"CAF\u00c9",
		        "image":"cafe.png"
		    },
		    {
		        "name":"GASEOSA",
		        "image":"gaseosa.png"
		    },
		    {
		        "name":"JUGO",
		        "image":"jugo.png"
		    },
		    {
		        "name":"LECHE",
		        "image":"leche.png"
		    },
		    {
		        "name":"T\u00c9",
		        "image":"te.png"
		    }
		]
	},
	{
		"name": "DEPORTES",
		"words": [
			{
		        "name":"BASKET",
		        "image":"basket.png"
		    },
		    {
		        "name":"F\u00daTBOL",
		        "image":"futbol.png"
		    },
		    {
		        "name":"GOLF",
		        "image":"golf.png"
		    },
		    {
		        "name":"HOCKEY",
		        "image":"hockey.png"
		    },
		    {
		        "name":"NATACI\u00d3N",
		        "image":"natacion.png"
		    },
		    {
		        "name":"TENIS",
		        "image":"tenis.png"
		    }
		]
	},
	{
		"name": "FAMILIA",
		"words": [
			{
		        "name":"ABUELA",
		        "image":"abuela.png"
		    },
		    {
		        "name":"ABUELO",
		        "image":"abuelo.png"
		    },
		    {
		        "name":"ABUELOS",
		        "image":"abuelos.png"
		    },
		    {
		        "name":"AMIGOS",
		        "image":"amigos.png"
		    },
		    {
		        "name":"FAMILIA",
		        "image":"familia.png"
		    },
		    {
		        "name":"HERMANA",
		        "image":"hermana.png"
		    },
		    {
		        "name":"HERMANO",
		        "image":"hermano.png"
		    },
		    {
		        "name":"MAM\u00c1",
		        "image":"mama.png"
		    },
		    {
		        "name":"PADRES",
		        "image":"padres.png"
		    },
		    {
		        "name":"PAP\u00c1",
		        "image":"papa.png"
		    },
		    {
		        "name":"PRIMA",
		        "image":"prima.png"
		    },
		    {
		        "name":"PRIMO",
		        "image":"primo.png"
		    }
		]
	},
	{
		"name": "FRUTAS",
		"words": [
			{
		        "name":"ANAN\u00c1",
		        "image":"anana.png"
		    },
		    {
		        "name":"BANANA",
		        "image":"banana.png"
		    },
		    {
		        "name":"COCO",
		        "image":"coco.png"
		    },
		    {
		        "name":"DURAZNO",
		        "image":"durazno.png"
		    },
		    {
		        "name":"FRUTILLA",
		        "image":"frutilla.png"
		    },
		    {
		        "name":"HIGO",
		        "image":"higo.png"
		    },
		    {
		        "name":"KIWI",
		        "image":"kiwi.png"
		    },
		    {
		        "name":"LIM\u00d3N",
		        "image":"limon.png"
		    },
		    {
		        "name":"MANGO",
		        "image":"mango.png"
		    },
		    {
		        "name":"MANZANA",
		        "image":"manzana.png"
		    },
		    {
		        "name":"NARANJA",
		        "image":"naranja.png"
		    },
		    {
		        "name":"PALTA",
		        "image":"palta.png"
		    },
		    {
		        "name":"PERA",
		        "image":"pera.png"
		    },
		    {
		        "name":"SANDIA",
		        "image":"sandia.png"
		    },
		    {
		        "name":"UVA",
		        "image":"uva.png"
		    }
		]
	},
	{
		"name": "PROFESIONES",
		"words": [
			{
		        "name":"AGRICULTOR",
		        "image":"agricultor.png"
		    },
		    {
		        "name":"ALBA\u00d1IL",
		        "image":"albanil.png"
		    },
		    {
		        "name":"BARRENDERO",
		        "image":"barrendero.png"
		    },
		    {
		        "name":"BOMBERO",
		        "image":"bombero.png"
		    },
		    {
		        "name":"CAJERO",
		        "image":"cajero.png"
		    },
		    {
		        "name":"CAMARERO",
		        "image":"camarero.png"
		    },
		    {
		        "name":"CARPINTERO",
		        "image":"carpintero.png"
		    },
		    {
		        "name":"CARTERO",
		        "image":"cartero.png"
		    },
		    {
		        "name":"ELECTRICISTA",
		        "image":"electricista.png"
		    },
		    {
		        "name":"ENFERMERO",
		        "image":"enfermero.png"
		    },
		    {
		        "name":"FONTANERO",
		        "image":"fontanero.png"
		    },
		    {
		        "name":"GRANJERO",
		        "image":"granjero.png"
		    },
		    {
		        "name":"JARDINERO",
		        "image":"jardinero.png"
		    },
		    {
		        "name":"MEC\u00c1NICO",
		        "image":"mecanico.png"
		    },
		    {
		        "name":"M\u00c9DICO",
		        "image":"medico.png"
		    },
		    {
		        "name":"PANADERO",
		        "image":"panadero.png"
		    },
		    {
		        "name":"PELUQUERO",
		        "image":"peluquero.png"
		    },
		    {
		        "name":"PERIODISTA",
		        "image":"periodista.png"
		    },
		    {
		        "name":"PESCADOR",
		        "image":"pescador.png"
		    },
		    {
		        "name":"PINTOR",
		        "image":"pintor.png"
		    },
		    {
		        "name":"POLICIA",
		        "image":"policia.png"
		    },
		    {
		        "name":"PROFESOR",
		        "image":"profesor.png"
		    },
		    {
		        "name":"VENDEDOR",
		        "image":"vendedor.png"
		    },
		    {
		        "name":"VETERINARIO",
		        "image":"veterinario.png"
		    }
		]
		
	},
	{
		"name": "ROPA",
		"words": [
			{
		        "name":"ABRIGO",
		        "image":"abrigo.png"
		    },
		    {
		        "name":"BOTAS",
		        "image":"botas.png"
		    },
		    {
		        "name":"BUFANDA",
		        "image":"bufanda.png"
		    },
		    {
		        "name":"BUZO",
		        "image":"buzo.png"
		    },
		    {
		        "name":"CAMISA",
		        "image":"camisa.png"
		    },
		    {
		        "name":"CHANCLAS",
		        "image":"chanclas.png"
		    },
		    {
		        "name":"CORBATA",
		        "image":"corbata.png"
		    },
		    {
		        "name":"FALDA",
		        "image":"falda.png"
		    },
		    {
		        "name":"GORRA",
		        "image":"gorra.png"
		    },
		    {
		        "name":"GORRO",
		        "image":"gorro.png"
		    },
		    {
		        "name":"GUANTES",
		        "image":"guantes.png"
		    },
		    {
		        "name":"MEDIAS",
		        "image":"medias.png"
		    },
		    {
		        "name":"PA\u00d1UELO",
		        "image":"panuelo.png"
		    },
		    {
		        "name":"PANTAL\u00d3N",
		        "image":"pantalon.png"
		    },
		    {
		        "name":"PANTAL\u00d3N CORTO",
		        "image":"pantaloncorto.png"
		    },
		    {
		        "name":"PIJAMA",
		        "image":"pijama.png"
		    },
		    {
		        "name":"REMERA MANGA CORTA",
		        "image":"remeramangacorta.png"
		    },
		    {
		        "name":"REMERA MANGA LARGA",
		        "image":"remeramangalarga.png"
		    },
		    {
		        "name":"SANDALIAS",
		        "image":"sandalias.png"
		    },
		    {
		        "name":"SOMBRERO",
		        "image":"sombrero.png"
		    },
		    {
		        "name":"SUDADERA",
		        "image":"sudadera.png"
		    },
		    {
		        "name":"ZAPATILLAS",
		        "image":"zapatillas.png"
		    },
		    {
		        "name":"ZAPATOS",
		        "image":"zapatos.png"
		    }
		]
		
	},
	{
		"name": "VERDURAS",
		"words": [
			{
		        "name":"ALCACHOFA",
		        "image":"alcachofa.png"
		    },
		    {
		        "name":"APIO",
		        "image":"apio.png"
		    },
		    {
		        "name":"BERENJENA",
		        "image":"berenjena.png"
		    },
		    {
		        "name":"BR\u00d3COLI",
		        "image":"brocoli.png"
		    },
		    {
		        "name":"CALABAZA",
		        "image":"calabaza.png"
		    },
		    {
		        "name":"CEBOLLA",
		        "image":"cebolla.png"
		    },
		    {
		        "name":"CHILE",
		        "image":"chile.png"
		    },
		    {
		        "name":"COLIFLOR",
		        "image":"coliflor.png"
		    },
		    {
		        "name":"MAIZ",
		        "image":"maiz.png"
		    },
		    {
		        "name":"MORR\u00d3N",
		        "image":"morron.png"
		    },
		    {
		        "name":"PAPA",
		        "image":"papa.png"
		    },
		    {
		        "name":"PEPINO",
		        "image":"pepino.png"
		    },
		    {
		        "name":"REMOLACHA",
		        "image":"remolacha.png"
		    },
		    {
		        "name":"TOMATE",
		        "image":"tomate.png"
		    },
		    {
		        "name":"ZANAHORIA",
		        "image":"zanahoria.png"
		    }
		]
	}
];