SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `categories` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `categories` (`id`, `name`) VALUES
(1, 'acciones'),
(2, 'animales'),
(3, 'bebidas'),
(4, 'deportes'),
(5, 'familia'),
(6, 'frutas'),
(7, 'profesiones'),
(8, 'ropa'),
(9, 'verduras');

CREATE TABLE `words` (
  `id` int(11) NOT NULL,
  `category_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `words` (`id`, `category_id`, `name`, `image`) VALUES
(1, 1, 'ABRAZAR', 'abrazar.png'),
(2, 1, 'ADORNAR', 'adornar.png'),
(3, 1, 'ARRUGAR', 'arrugar.png'),
(4, 1, 'AYUDAR', 'ayudar.png'),
(5, 1, 'BAILAR', 'bailar.png'),
(6, 1, 'BAÑAR', 'banar.png'),
(7, 1, 'BEBER', 'beber.png'),
(8, 1, 'BESAR', 'besar.png'),
(9, 1, 'BORRAR', 'borrar.png'),
(10, 1, 'CAER', 'caer.png'),
(11, 1, 'CAMINAR', 'caminar.png'),
(12, 1, 'CANTAR', 'cantar.png'),
(13, 1, 'CERRAR', 'cerrar.png'),
(14, 1, 'CHUPAR', 'chupar.png'),
(15, 1, 'COMER', 'comer.png'),
(16, 1, 'CORRER', 'correr.png'),
(17, 1, 'COSER', 'coser.png'),
(18, 1, 'DAR', 'dar.png'),
(19, 1, 'DISCUTIR', 'discutir.png'),
(20, 1, 'DORMIR', 'dormir.png'),
(21, 1, 'EMPUJAR', 'empujar.png'),
(22, 1, 'ENCENDER', 'encender.png'),
(23, 1, 'ENSEÑAR', 'ensenar.png'),
(24, 1, 'ENTRAR', 'entrar.png'),
(25, 1, 'ESCONDER', 'esconder.png'),
(26, 1, 'ESCRIBIR', 'escribir.png'),
(27, 1, 'ESCUCHAR', 'escuchar.png'),
(28, 1, 'JUGAR', 'jugar.png'),
(29, 1, 'LAVAR', 'lavar.png'),
(30, 1, 'LAVARMANOS', 'lavarmanos.png'),
(31, 1, 'LEER', 'leer.png'),
(32, 1, 'LIMPIAR', 'limpiar.png'),
(33, 1, 'LLAMAR', 'llamar.png'),
(35, 1, 'LLORAR', 'llorar.png'),
(36, 1, 'MIRAR', 'mirar.png'),
(37, 1, 'MIRARSE', 'mirarse.png'),
(38, 1, 'NADAR', 'nadar.png'),
(39, 1, 'OIR', 'oir.png'),
(40, 1, 'OLER', 'oler.png'),
(41, 1, 'PATINAR', 'patinar.png'),
(42, 1, 'PEGAR', 'pegar.png'),
(43, 1, 'PEINAR', 'peinar.png'),
(44, 1, 'PESCAR', 'pescar.png'),
(45, 1, 'PINTAR', 'pintar.png'),
(46, 1, 'QUERER', 'querer.png'),
(47, 1, 'REIR', 'reir.png'),
(48, 1, 'ROBAR', 'robar.png'),
(49, 1, 'ROMPER', 'romper.png'),
(50, 1, 'SALTAR', 'saltar.png'),
(51, 1, 'SALUDAR', 'saludar.png'),
(52, 1, 'SECAR', 'secar.png'),
(53, 1, 'SOPLAR', 'soplar.png'),
(54, 1, 'SUJETAR', 'sujetar.png'),
(55, 1, 'TOCAR', 'tocar.png'),
(56, 1, 'TRABAJAR', 'trabajar.png'),
(57, 1, 'VESTIR', 'vestir.png'),
(58, 2, 'ABEJA', 'abeja.png'),
(59, 2, 'ÁGUILA', 'aguila.png'),
(60, 2, 'ARAÑA', 'arana.png'),
(61, 2, 'BISONTE', 'bisonte.png'),
(62, 2, 'BUHO', 'buho.png'),
(63, 2, 'CABALLO', 'caballo.png'),
(64, 2, 'CABRA', 'cabra.png'),
(65, 2, 'CALAMAR', 'calamar.png'),
(66, 2, 'CAMALEON', 'camaleon.png'),
(67, 2, 'CANGREJO', 'cangrejo.png'),
(68, 2, 'CANGURO', 'canguro.png'),
(69, 2, 'CASTOR', 'castor.png'),
(70, 2, 'CERDO', 'cerdo.png'),
(71, 2, 'CIENPIÉS', 'cienpies.png'),
(72, 2, 'CIERVO', 'ciervo.png'),
(73, 2, 'COCODRILO', 'cocodrilo.png'),
(74, 2, 'CONEJO', 'conejo.png'),
(75, 2, 'DELFÍN', 'delfin.png'),
(76, 2, 'ELEFANTE', 'elefante.png'),
(77, 2, 'ERIZO', 'erizo.png'),
(78, 2, 'ESCORPIÓN', 'escorpion.png'),
(79, 2, 'ESTRELLA DE MAR', 'estrellademar.png'),
(80, 2, 'FOCA', 'foca.png'),
(81, 2, 'GALLO', 'gallo.png'),
(82, 2, 'GATO', 'gato.png'),
(83, 2, 'HIPOPÓTAMO', 'hipopotamo.png'),
(84, 2, 'INSECTO', 'insecto.png'),
(85, 2, 'JABALÍ', 'jabali.png'),
(86, 2, 'JIRAFA', 'jirafa.png'),
(87, 2, 'KOALA', 'koala.png'),
(88, 2, 'LEÓN', 'leon.png'),
(89, 2, 'LLAMA', 'llama.png'),
(90, 2, 'LOBO', 'lobo.png'),
(91, 2, 'LORO', 'loro.png'),
(92, 2, 'MAPACHE', 'mapache.png'),
(93, 2, 'MARIPOSA', 'mariposa.png'),
(94, 2, 'ORCA', 'orca.png'),
(95, 2, 'OSO', 'oso.png'),
(96, 2, 'OVEJA', 'oveja.png'),
(97, 2, 'PALOMA', 'paloma.png'),
(98, 2, 'PANDA', 'panda.png'),
(99, 2, 'PATO', 'pato.png'),
(100, 2, 'PEREZOSO', 'perezoso.png'),
(101, 2, 'PERRO', 'perro.png'),
(102, 2, 'PEZ', 'pez.png'),
(103, 2, 'PINGÜINO', 'pinguino.png'),
(104, 2, 'RANA', 'rana.png'),
(105, 2, 'RATÓN', 'raton.png'),
(106, 2, 'SERPIENTE', 'serpiente.png'),
(107, 2, 'TIBURÓN', 'tiburon.png'),
(108, 2, 'TIGRE', 'tigre.png'),
(109, 2, 'TORTUGA', 'tortuga.png'),
(110, 2, 'VACA', 'vaca.png'),
(111, 2, 'ZORRO', 'zorro.png'),
(112, 3, 'AGUA', 'agua.png'),
(113, 3, 'CAFÉ', 'cafe.png'),
(114, 3, 'GASEOSA', 'gaseosa.png'),
(115, 3, 'JUGO', 'jugo.png'),
(116, 3, 'LECHE', 'leche.png'),
(117, 3, 'TÉ', 'te.png'),
(118, 4, 'BASKET', 'basket.png'),
(119, 4, 'FÚTBOL', 'futbol.png'),
(120, 4, 'GOLF', 'golf.png'),
(121, 4, 'HOCKEY', 'hockey.png'),
(122, 4, 'NATACIÓN', 'natacion.png'),
(123, 4, 'TENIS', 'tenis.png'),
(124, 5, 'ABUELA', 'abuela.png'),
(125, 5, 'ABUELO', 'abuelo.png'),
(126, 5, 'ABUELOS', 'abuelos.png'),
(127, 5, 'AMIGOS', 'amigos.png'),
(128, 5, 'FAMILIA', 'familia.png'),
(129, 5, 'HERMANA', 'hermana.png'),
(130, 5, 'HERMANO', 'hermano.png'),
(131, 5, 'MAMÁ', 'mama.png'),
(132, 5, 'PADRES', 'padres.png'),
(133, 5, 'PAPÁ', 'papa.png'),
(134, 5, 'PRIMA', 'prima.png'),
(135, 5, 'PRIMO', 'primo.png'),
(136, 6, 'ANANÁ', 'anana.png'),
(137, 6, 'BANANA', 'banana.png'),
(138, 6, 'COCO', 'coco.png'),
(139, 6, 'DURAZNO', 'durazno.png'),
(140, 6, 'FRUTILLA', 'frutilla.png'),
(141, 6, 'HIGO', 'higo.png'),
(142, 6, 'KIWI', 'kiwi.png'),
(143, 6, 'LIMÓN', 'limon.png'),
(144, 6, 'MANGO', 'mango.png'),
(145, 6, 'MANZANA', 'manzana.png'),
(146, 6, 'NARANJA', 'naranja.png'),
(147, 6, 'PALTA', 'palta.png'),
(148, 6, 'PERA', 'pera.png'),
(149, 6, 'SANDIA', 'sandia.png'),
(150, 6, 'UVA', 'uva.png'),
(151, 7, 'AGRICULTOR', 'agricultor.png'),
(152, 7, 'ALBAÑIL', 'albanil.png'),
(153, 7, 'BARRENDERO', 'barrendero.png'),
(154, 7, 'BOMBERO', 'bombero.png'),
(155, 7, 'CAJERO', 'cajero.png'),
(156, 7, 'CAMARERO', 'camarero.png'),
(157, 7, 'CARPINTERO', 'carpintero.png'),
(158, 7, 'CARTERO', 'cartero.png'),
(159, 7, 'ELECTRICISTA', 'electricista.png'),
(160, 7, 'ENFERMERO', 'enfermero.png'),
(161, 7, 'FONTANERO', 'fontanero.png'),
(162, 7, 'GRANJERO', 'granjero.png'),
(163, 7, 'JARDINERO', 'jardinero.png'),
(164, 7, 'MECÁNICO', 'mecanico.png'),
(165, 7, 'MÉDICO', 'medico.png'),
(166, 7, 'PANADERO', 'panadero.png'),
(167, 7, 'PELUQUERO', 'peluquero.png'),
(168, 7, 'PERIODISTA', 'periodista.png'),
(169, 7, 'PESCADOR', 'pescador.png'),
(170, 7, 'PINTOR', 'pintor.png'),
(171, 7, 'POLICIA', 'policia.png'),
(172, 7, 'PROFESOR', 'profesor.png'),
(173, 7, 'VENDEDOR', 'vendedor.png'),
(174, 7, 'VETERINARIO', 'veterinario.png'),
(175, 8, 'ABRIGO', 'abrigo.png'),
(176, 8, 'BOTAS', 'botas.png'),
(177, 8, 'BUFANDA', 'bufanda.png'),
(178, 8, 'BUZO', 'buzo.png'),
(179, 8, 'CAMISA', 'camisa.png'),
(180, 8, 'CHANCLAS', 'chanclas.png'),
(181, 8, 'CORBATA', 'corbata.png'),
(182, 8, 'FALDA', 'falda.png'),
(183, 8, 'GORRA', 'gorra.png'),
(184, 8, 'GORRO', 'gorro.png'),
(185, 8, 'GUANTES', 'guantes.png'),
(186, 8, 'MEDIAS', 'medias.png'),
(187, 8, 'PAÑUELO', 'panuelo.png'),
(188, 8, 'PANTALÓN', 'pantalon.png'),
(189, 8, 'PANTALÓN CORTO', 'pantaloncorto.png'),
(190, 8, 'PIJAMA', 'pijama.png'),
(191, 8, 'REMERA MANGA CORTA', 'remeramangacorta.png'),
(192, 8, 'REMERA MANGA LARGA', 'remeramangalarga.png'),
(193, 8, 'SANDALIAS', 'sandalias.png'),
(194, 8, 'SOMBRERO', 'sombrero.png'),
(195, 8, 'SUDADERA', 'sudadera.png'),
(196, 8, 'ZAPATILLAS', 'zapatillas.png'),
(197, 8, 'ZAPATOS', 'zapatos.png'),
(198, 9, 'ALCACHOFA', 'alcachofa.png'),
(199, 9, 'APIO', 'apio.png'),
(200, 9, 'BERENJENA', 'berenjena.png'),
(201, 9, 'BRÓCOLI', 'brocoli.png'),
(202, 9, 'CALABAZA', 'calabaza.png'),
(203, 9, 'CEBOLLA', 'cebolla.png'),
(204, 9, 'CHILE', 'chile.png'),
(205, 9, 'COLIFLOR', 'coliflor.png'),
(206, 9, 'MAIZ', 'maiz.png'),
(207, 9, 'MORRÓN', 'morron.png'),
(208, 9, 'PAPA', 'papa.png'),
(209, 9, 'PEPINO', 'pepino.png'),
(210, 9, 'REMOLACHA', 'remolacha.png'),
(211, 9, 'TOMATE', 'tomate.png'),
(212, 9, 'ZANAHORIA', 'zanahoria.png');

ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `id` (`id`);

ALTER TABLE `words`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `id` (`id`);

ALTER TABLE `categories`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;

ALTER TABLE `words`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=213;
COMMIT;